dataset_name: LFW
checkpoints_path: ./checkpoints

text_encoder_path: "./checkpoints/celeba/TGFR/BERT_arcface_ir_50/linear/encoder_BERT_linear_16.pth"
image_encoder_path: "./checkpoints/celeba/TGFR/BERT_arcface_ir_50/linear/fusion_linear_arcface_16.pth"
backend_path: "./weights/finetuned/arcface_face2text.pth"

# machine setup 
batch_size: 64

# model arch
img_size: 112
ch_size: 3
model_type: adaface #adaface, magface, arcface
architecture: ir_50
printing_attr: False  

# encoder settings
en_type: BERT        
embedding_dim: 256
bert_type: bert 


# fusion arch
is_ident: False           
fusion_type: linear #linear, CMF
fusion_final_dim: 512 
gl_img_dim: 256
gl_text_dim: 256


# flags
printing_attr: True      
do_test: True