dataset_name: face2text #celeba
checkpoints_path: ./checkpoints

text_encoder_path: "./checkpoints/celeba/TGFR/BERT_arcface/linear/encoder_BERT_linear_18.pth"
image_encoder_path: "./checkpoints/celeba/TGFR/BERT_arcface/linear/fusion_linear_arcface_18.pth"


# machine setup 
batch_size: 64


# model arch
img_size: 112
model_type: arcface #arcface, magface, arcface
ch_size: 3


# encoder settings
en_type: BERT        
embedding_dim: 256
bert_type: bert 

# fusion arch
fusion_type: fcfm #linear, CMF
fusion_final_dim: 544 
gl_img_dim: 256

#save
roc_file: LSTM_arc_fcfm_face2text 
is_roc: False   
is_ident: False      

# flags
do_test: True