#### configuration and directory
dataset_name: celeba
checkpoints_path: ./checkpoints
backend_path: "./weights/finetuned/adaface_celeba.pth"


# losses
is_DAMSM: False            
is_CLIP:  False 
is_CMP: False
is_ITC: False 
is_KD: False
is_ident_loss: True
is_attr_loss: False          

lambda_attr: 12
lambda_cmp: 1
lambda_itc: 1
lambda_clip: 1
lambda_kd: 0.1
lambda_id:  1
lambda_f: 3

printing_attr: False  

# model arch 
img_size: 112 
model_type: adaface #arcface, magface, adaface
architecture: ir_18     
ch_size: 3           

min_lr_bert: 0.00004 #(1e-5 for BERT)
lr_head: 0.003
clip_max_norm: 1.0

#trainng settings
batch_size: 8
max_epoch: 14 
test_interval: 2
save_interval: 1
temperature: 5.0

# flags
do_test: True   
is_roc: False
split: "train"


# encoder
TRAIN:
    FLAG: True
    SMOOTH:
        GAMMA1: 4.0  
        GAMMA2: 5.0
        GAMMA3: 10.0

en_type: "BERT"   
bert_type: "bert" #bert 

# fusion arch
fusion_type: linear
is_ident: False
fusion_final_dim: 512   
gl_img_dim: 256
gl_text_dim: 256