#### configuration and directory
dataset_name: face2text #celeba
checkpoints_path: ./checkpoints

# losses
is_SDM: False 
is_DAMSM: False           
is_CLIP:  False 
is_CMP: False
is_ITC: False 
is_KD: False
is_ident_loss: True
is_attr_loss: False       

lambda_attr: 15
lambda_cmp: 1
lambda_sdm: 0.2
lambda_itc: 1
lambda_clip: 1
lambda_kd: 0.1
lambda_id:  1
lambda_f: 3

# model arch 
img_size: 112 
model_type: arcface #arcface, magface, adaface     
ch_size: 3           

min_lr_bert: 0.00004 #(1e-5 for BERT)
lr_head: 0.003
clip_max_norm: 1.0

#trainng settings
batch_size: 8
max_epoch: 20
test_interval: 2
save_interval: 1
temperature: 5.0

# flags
do_test: True   
is_roc: False
is_ident: False 

# encoder
TRAIN:
    FLAG: True
    SMOOTH:
        GAMMA1: 4.0  
        GAMMA2: 5.0
        GAMMA3: 10.0

en_type: "BERT"   
bert_type: "bert" #bert 

# fusion arch
fusion_type: linear
fusion_final_dim: 548   
gl_img_dim: 256
gl_text_dim: 256